### ISSUE TITLE
Consider dropping php-5.6 and php-7.0 versions

### ISSUE THREAD

**Issue by peter279k** [alexsoft/leftpad#7]
As title, the currently supported PHP version is `php-7.1`.

And I think we can consider dropping `php-5.6` and `php-7.0` version supports in the future released version.

**Comment by alexsoft** [comment]
@peter279k hello. thanks for creating this issue. I am just wondering, are you using this package? 🤔

**Comment by peter279k** [comment]
> @peter279k hello. thanks for creating this issue. I am just wondering, are you using this package?

@alexsoft, thanks for your reply. I use this package for my experimental project.

**Comment by alexsoft** [comment]
Updated to support 7.4+
